### ISSUE TITLE
Resolving @radpack/server inside @radpack/server creates a forced dependency

### ISSUE THREAD

**Issue by doug-mccuen-kr** [godaddy/radpack#37]
https://github.com/godaddy/radpack/blob/eed80081c8a4ad3fc2db7eaac67a7613427d259f/packages/server/src/radpack.js#L9

We are rolling up @radpack/server inside our custom library, and would like our consumers **not** to have to set @radpack/server as an additional dependency.  The line referenced above forces that issue.  Can you help us understand why that require.resolve statement is needed, and how we might achieve our desired result?

Thanks!

**Comment by doug-mccuen-kr** [comment]
We are bundling for node, and the result is a single file that won't be able to `require.resolve('@radpack/server')` unless our consumers specify that dependency.  Our "locally installed dependencies" are rolled up.  

Is there a way to isolate the `require.resolve` within the local proxy middleware (if that is where it is needed) and/or allow it to fail gracefully?  As a top level constant in this file it throws an error for us right out of the gate.

**Comment by trhinehart-godaddy** [comment]
I see, then yes you would need to list `@radpack/server` and `@radpack/core` as `peerDependencies` for that `require.resolve` to properly work, or as `dependencies` if your consumers are using your library via `node_modules`.

I'm open to accepting a PR making `SERVER_ABS_PATH` optional if it solves your issue.
