### ISSUE TITLE
External React dependency

### ISSUE THREAD

**Issue by bpolge-kr** [godaddy/radpack#56]
We're trying to bundle a federated React component using the `rollup-plugin` and we're running into an issue where it says it can't find module `React`... which is the expected behavior since it is supposed to be a peer dependency and not included in the bundle.

What configuration options do we need to pass the the plugin to make this work?

**Comment by trhinehart-godaddy** [comment]
Radpack is a runtime dependency management tool, so if a dependency like `react` is not to be bundled with the library, it would either need to be exposed as an export of your registry or expose it globally via the application consuming your library and update your library rollup configuration to use something like `rollup-plugin-external-globals`
